### ISSUE TITLE
Got command error in LunarVim

### ISSUE THREAD

**Issue by candeemis** [michaelrommel/nvim-silicon#14]
Hi, I used the default configs provided and when run, got the following error.

<img width="1366" alt="Screenshot 2024-03-06 at 13 50 16" src="https://github.com/michaelrommel/nvim-silicon/assets/53427821/07865364-e2d8-4a69-821d-e7ca47428c5f">

I selected some text in visual mode and ran `Silicon` command, that's how I got the error.

Am I missing something? 🤔

**Comment by michaelrommel** [comment]
Hi there,

yes, you are missing the prerequisite `silicon` binary, which needs to be installed on your system and in your $PATH. The upstream project is here: https://github.com/Aloxaf/silicon

But you can install it on a mac with `brew install silicon` or if you have installed rust, the compilation and installation is very easy as well: `cargo install silicon`.

Maybe I should emphasize in the readme how the tool can be installed...

Could you try to install `silicon` on your system and tell me how it went?

Thanks a lot!

  Michael.

**Comment by candeemis** [comment]
It worked, however I had to remove `NF` from `font = "VictorMono NF=34;Noto Emoji=34"` since I couldn't find VictorMono font with `NF` postfix. Maybe I am missing something.

![2024-03-06T14-25-47_code](https://github.com/michaelrommel/nvim-silicon/assets/53427821/989305a3-c457-4fe1-9c1e-ee1ade9dc02b)

**Comment by candeemis** [comment]
Maybe that is enough for me, therefore I would close this issue. Feel free to reopen, if you need more details from me.

**Comment by michaelrommel** [comment]
Thank you! Yes, the font setting was merely an example, `silicon` would still fallback to some other builtin font. I guess I did not put too much emphasis on constructing a typeface recommendation, because I think every terminal user has a strong opinion what the perfect font/typeface is and in the end in 90% of the time, the font setting would be overridden by users 😏
The `NF` stands for NerdFont. That is a project that embeds a lot of special unicode characters in normal fonts, so that neovim and plugins look nice. You can download many prepatched fonts from their website: https://www.nerdfonts.com/font-downloads
