### ISSUE TITLE
No font found for character `ỏ`[warning]

### ISSUE THREAD

**Issue by ugotuan** [michaelrommel/nvim-silicon#19]
When copying the image, the character 'ỏ' is missing because it cannot be recognized. How can this be fixed, Michael?
<img width="1278" alt="image" src="https://github.com/michaelrommel/nvim-silicon/assets/146410900/f867bc89-f035-45b7-9d83-d0615b5f5896">

**Comment by SinhLong** [comment]
> When copying the image, the character 'ỏ' is missing because it cannot be recognized. How can this be fixed, Michael?

same issue here.

**Comment by michaelrommel** [comment]
Hello both,

it can be fixed by installing a font that contains a glyph for that character. I have tested this with a simple example rust code:

```
fn main() {
    println!("No font found for character ỏ[warning]")
}
```
and with my patched font Victor Mono it worked out of the box.

![image](https://github.com/michaelrommel/nvim-silicon/assets/919935/41a41d54-c3c7-494b-b784-4acb58a88594)

I think you just need to find a font with a large glyph range and reference that in your silicon configuration file, like as

```
{
	"michaelrommel/nvim-silicon",
	lazy = true,
	cmd = "Silicon",
	main = "nvim-silicon",
	opts = {
		-- Configuration here, or leave empty to use defaults
		font = "VictorMono NF=34;Noto Emoji",
	}
},
```

**Comment by michaelrommel** [comment]
Dear all,

has installing a complete font solved your problem? E.g. https://rubjo.github.io/victor-mono/

If so, would you mind closing the issue?

Thanks!

  Michael.

**Comment by ugotuan** [comment]
It's worked. Thank you very much
